name: Release

on:
  push:
    branches: [main]

jobs:
  cut-release:
    name: runner / cut-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}

      - run: |
          VERSION=`echo ${{ steps.tag.outputs.new_tag }} | cut -d. -f1`
          if [ "${VERSION}" != "undefined" ]; then
            git tag -f "${VERSION}"
            git push -f --tags
          fi

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
